In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_resume = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Future_ML_03/data/Resume/Resume.csv')
df_jobs = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Future_ML_03/data/Job_description_dataset/monster_com-job_sample.csv')

In [3]:
df_resume.sample(5)

,ID,Resume_str,Resume_html,Category
1117,26291616,IT CONSULTANT Career Overview ...,"<div class=""fontsize fontface vmargins hmargin...",CONSULTANT
1548,29494962,SECRETARY - FINANCE DIVISION Su...,"<div class=""fontsize fontface vmargins hmargin...",FINANCE
125,22567495,INSTRUCTIONAL DESIGNER Summar...,"<div class=""fontsize fontface vmargins hmargin...",DESIGNER
141,25422388,GRAPHIC DESIGNER Summary Dr...,"<div class=""fontsize fontface vmargins hmargin...",DESIGNER
2461,17694572,ADMINISTRATIVE MANAGER Profes...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION

In [4]:
df_jobs.sample(5)

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
8450,United States of America,US,NaN,No,jobs.monster.com,Position Description · Ensure the imp...,Assistant Contractor Special Security Officer ...,Full Time,"Arlington, VA 22202",NaN,http://jobview.monster.com/assistant-contracto...,NaN,Experienced (Non-Manager),15e757f424de69a2d5ba5a21db45e1d3
3061,United States of America,US,NaN,No,jobs.monster.com,"Our Client, a worldwide social media company, ...",Administrative Assistant Job in Mountain View,Full Time Employee,"Mountain View, CA",NaN,http://jobview.monster.com/Administrative-Assi...,NaN,General/Other: IT/Software Development,e40cc948be05ff8287f66aafed7ca526
9755,United States of America,US,NaN,No,jobs.monster.com,Seamless CIS is looking for Independent and Su...,Installation and Service Technician Job in Kan...,Full Time,"Kansas City, MO",Other/Not Classified,http://jobview.monster.com/Installation-Servic...,NaN,NaN,69c2bfb2095ba3314ea0dea236ea59f5
13737,United States of America,US,NaN,No,jobs.monster.com,"Independently plan, coordinate, and report on ...",Senior Quality Assurance Scientist Job in Chaska,Full Time,"Chaska, MN 55318",Biotechnology/Pharmaceuticals,http://jobview.monster.com/Senior-Quality-Assu...,NaN,Experienced (Non-Manager),1f72ab9502411ce09d349cb79087ebe5
2356,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job Job Title: HR Ma...,Level One Personnel Job Application for HR Man...,"Full Time, Employee","Job Title: HR ManagerLocation: Frederick, MDDu...",Staffing/Employment Agencies,http://jobview.monster.com/hr-manager-job-fred...,NaN,NaN,a157c8c0a0cf52c1b10da12f0bc8a655

In [5]:
print(df_resume.shape, df_jobs.shape)

(2484, 4) (22000, 14)

In [6]:
print(df_resume['Category'].value_counts())

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
ENGINEERING               118
ACCOUNTANT                118
FINANCE                   118
FITNESS                   117
AVIATION                  117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [7]:
print(df_resume['Category'].nunique())

24

In [8]:
print(df_jobs.columns.tolist())

['country', 'country_code', 'date_added', 'has_expired', 'job_board', 'job_description', 'job_title', 'job_type', 'location', 'organization', 'page_url', 'salary', 'sector', 'uniq_id']

In [9]:
df_resume[df_resume['Category']=='ENGINEERING']['Resume_str'].iloc[0]

'         ENGINEERING TECHNICIAN           Highlights        PC Operating Systems, Microsoft Office, Outlook, Internet              Experience      Company Name    City  ,   State    Engineering Technician   01/2014   to   Current       Analyze documentation to ensure production accuracy.  Use MS Excel and PowerPoint to create presentations and spreadsheets.  Engage engineering to resolve production issues.  Create and maintain production training certifications.  Generate training matrix to determine and eliminate training gaps.  Conduct weekly safety audits to reduce accidents and ensure safe workplace.  Use Oracle to track material transactions, verify vendor and material information, and print transfer orders.  Point of contact for Vendor, OSSR, PM, Buyer, Planner and Manager for many part issues.  Initiate stock purge of suspected discrepant material and coordinate the inspection and disposition of the material.  Manage weekly MRB meetings and provide weekly DMR disposition metrics.  Work with suppliers to resolve issues with parts found on the manufacturing floor.  Effectively manage all DMR/RTS material initiated by test, remotes and build activities.  Support the "TXZ cover recycle" effort through SR initiation and material preparation for shipment to Japan.          Company Name    City  ,   State    Consultant   12/2012         Analyzed and determined factors affecting networking needs including hardware and attenuation/interference.  Set up dual network infrastructure utilizing both wired and wireless routers.  Austin Free-Net\t\t\t\t\t\t\t\t\tDec 2012.  Assist in the design of deployment server for the distribution of updates to various computer labs.          Company Name    City  ,   State    Engineering Technician   01/2011   to   12/2013       Maintain documentation and records.  Analyze documentation to ensure production accuracy.  Managed incoming product and shipping process.  Assist Manufacturing Engineering team on new product production and quality procedures.  Review production orders and provide updates to ensure production accuracy.          Company Name    City  ,   State    Manufacturing Lead   07/2004   to   12/2010       Analyzed production orders and schedules to ascertain types, quantities and specifications.  Planned production operations, establishing priorities and sequences.  Utilized Microsoft Office to document and update status reports.  Analyzed production reports and resolved operational and manufacturing problems to ensure scheduling needs.  Provided training, supervision and logistics coordination.  Maintain training certification and documentation.  Aligned internal resources to achieve on-time and budget performance objectives.  Analyzed reports and consulted with quality, management, and engineering personnel to solve problems.  Interface with customer to monitor project progress and cost.  Assisted in administration of software database.  Installation of network systems.  Assisted in implementing production software in a high volume manufacturing environment.  Coordinate product transition and support team.          Education        Business Administration   2019     University of Phoenix\tTexas          Business Administration        Professional Affiliations    Information Systems Security Association (ISSA)      Skills    budget, hardware, network systems, database, Dec, documentation, inspection, logistics, meetings, MS Excel, Microsoft Office, Outlook, PowerPoint, network, networking, Operating Systems, Oracle, personnel, presentations, progress, quality, Maintain documentation, routers, safety, scheduling, shipping, spreadsheets, supervision   '

In [10]:
print(df_jobs['sector'].value_counts().head(30))
print(df_jobs['sector'].isnull().sum())

sector
Experienced (Non-Manager)                      4594
Medical/Health                                 1254
Entry Level                                    1172
Sales/Retail/Business Development               938
Manager (Manager/Supervisor of Staff)           900
IT/Software Development                         861
Project/Program Management                      790
Accounting/Finance/Insurance                    742
Food Services/Hospitality                       633
Installation/Maintenance/Repair                 574
Manufacturing/Production/Operations             544
Logistics/Transportation                        371
Customer Support/Client Care                    328
Quality Assurance/Safety                        323
Security/Protective Services                    311
Marketing/Product                               311
Administrative/Clerical                         271
Legal                                           237
Human Resources                                 205
Engineering                                     153
Business/Strategic Management                   124
Biotech/R&D/Science                             121
Education/Training                              115
General/Other: IT/Software Development          112
Building Construction/Skilled Trades             91
General/Other: Medical/Health                    84
Executive (SVP, VP, Department Head, etc)        67
Other                                            59
Student (High School)                            48
Environmental/Geological Testing & Analysis      39
Name: count, dtype: int64
5194

In [11]:
sector_category_map = {
    'INFORMATION-TECHNOLOGY': 'IT/Software Development',
    'ENGINEERNG': 'Engineering',
    'FINANCE': 'Accounting/Finance/Insurance',
    'SALES': 'Sales/Retail/Business Development',
    'HR': 'Human Resources',
    'HEALTHCARE': 'Medical/Health'
}

for resume_cat, sector in sector_category_map.items():
  sample = df_jobs[df_jobs['sector'] == sector][['job_title', 'job_description']].head(3)
  print(f"---{resume_cat}({sector})")
  print(sample['job_title'].tolist())
  print()

---INFORMATION-TECHNOLOGY(IT/Software Development)
['IT Support Technician Job in Madison', 'Scrum Master Job in Denver', 'QA Testing Analyst Job in Denver']

---ENGINEERNG(Engineering)
['Sr. Process Engineer', 'RF System Technician', 'Software Engineer Job in Fort Wayne']

---FINANCE(Accounting/Finance/Insurance)
['Real Estate Underwriter -Jr Job in Houston', 'Accounts Receivable - Commercial Real Estate Job in Denver', 'Senior Accountant/Analyst Job in Denver']

---SALES(Sales/Retail/Business Development)
['Financial Advisor / Financial Sales Representative- Full Time Sales', 'Service Manager Job in Denver', 'Bilingual Newborn Photographer/Sales Representative (Part-Time) - (Houston']

---HR(Human Resources)
['Payroll Analyst Job in Portland', 'Agency Recruiter Job in Denver', 'Human Resources Manager Job in Dallas']

---HEALTHCARE(Medical/Health)
['Respiratory Therapist PRN Nights - Kindred Hospital Medical Center Job in Houston', 'Registered Nurse - Clinic Job in Houston', 'Registered Nurse ICU Full Time Days - Kindred Hospital Town and Country Job in Houston']

In [12]:
print(df_jobs[df_jobs['sector'] == 'Sales/Retail/Business Development']['job_title'].head(15).tolist())

['Financial Advisor / Financial Sales Representative- Full Time Sales', 'Service Manager Job in Denver', 'Bilingual Newborn Photographer/Sales Representative (Part-Time) - (Houston', 'Hospitality Sales Specialist in Reading', 'Route Sales Representative Job in West Chester', "Macy's **Seasonal Holiday Retail Sales** Part Time: Dallas Galleria Job in Dallas", 'Sales Professional Job in Las Vegas', 'Retail Reset Merchandiser Kroger Part Time Job in Las Vegas', 'Event Specialist Part Time Sales Job in Henderson', 'Sales Professional Job in Las Vegas', 'Event Specialist Part Time Sales Job in Maryville', 'Territory Sales Account Manager - Telecommunications Job in Cherry Hill', 'Regional Sales Manager - Mountain Region Job in Aurora', 'Real Estate Sales - Licensed - Leads provided - Greater Dallas Area Job in Arlington', 'Sr Program Professional Job in Dallas']

In [13]:
print(df_jobs[df_jobs['sector'] == 'Accounting/Finance/Insurance']['job_title'].head(15).tolist())

['Real Estate Underwriter -Jr Job in Houston', 'Accounts Receivable - Commercial Real Estate Job in Denver', 'Senior Accountant/Analyst Job in Denver', 'Senior Tax Manager Job in Denver', 'Tax Senior Job in Houston', 'Insurance Sales - Customer Service Job in Eden Prairie', 'Director', 'Controller Job in Las Vegas', 'Staff Accountant Job in Las Vegas', 'Financial Professional Associate Job in Chalfont', 'Accounts Payable Specialist Job in San Diego', 'Accounts Payable Job in Boston', 'Senior Project Launch Analyst', 'Accounts Payable Specialist Job in Grand Rapids', 'Business Development Rep / BB Sales / Outside Sales Job in South San Francisco']

 Note :- We Got Our Final List of Jobs Description by Analyzing the Jobs_Description. These Jobs_Description are Chosen on the Principle that any Job_Title must not Overlap with any other Sector of the Job.

In [14]:
print(df_jobs[df_jobs['sector'] == 'Engineering']['job_title'].head(30).tolist())

['Sr. Process Engineer', 'RF System Technician', 'Software Engineer Job in Fort Wayne', 'Project Engineer Job in Dayton', 'Quality Engineer Job in Durham', 'Project Manager Job in Dayton', 'Validation Engineer Job in Andover', 'Custom Development Engineer Job in Greenville', 'Systems Engineer – Security System Designer Job in Los Angeles', 'Support Agent - GPS Systems Job in Racine', 'Reference Solutions Architect Job in Seattle', 'Strategic Partners Solutions Architect Job in Seattle', 'Technical Services Representative Job in Wylie', 'Machine Operator Job in Portage', 'Process Manufacturing Engineer Job in Harrisburg', 'Field Application Engineer Job in Anderson', 'Strategic Partners Solutions Architect Job in San Francisco', 'Business Analyst Job in Santa Cruz', 'Packaging Engineer Job in Chicago', 'Project Manager Job in Solon', 'Production Engineer - Injection Molding Job in Clinton', 'PROJECT MANAGER/CIVIL ENGINEER - TRAFFIC Job in Thornton', 'RF Engineer Job in Denver', 'Maintenance Manager Job in Dallas', 'Process Engineer Job in Atlanta', 'Engineering Manager Job in Atlanta', 'DevOps Job in Atlanta', 'Electrical Engineer', 'Senior Project Manager - Electric Job in Austin', 'Field Engineer II Job in Houston']

In [15]:
for title in ['Quality Engineer Job in Durham', 'Packaging Engineer Job in Chicago', 'Electrical Engineer']:
  text = df_jobs[df_jobs['job_title'] == title]['job_description'].iloc[0]
  print(f"{title} ----> ")
  print(text[:600])
  print()

Quality Engineer Job in Durham ---->
Experis Engineering has an immediate opening for a Quality Engineer. The Quality Engineer will create inspection criteria, review drawings, and suggest measurement methods, support validations, route deviations and support product movement throughout the facility.The Quality Engineer will also have the opportunity to:Develop, modify, apply and maintain quality standards and protocol for processing materials into partially finished or finished materials product.Collaborate with engineering and manufacturing functions to ensure quality standards are in place.Devise and implement methods and proc

Packaging Engineer Job in Chicago ---->
The Packaging Engineer works with the Packaging Innovation PM and Packaging Engineering teams to create a pipeline of impactful packaging related concepts, technologies, processes, methodologies, materials and supporting data. The work engages every organization that utilizes device packaging before and following pack-out including R&D, OPS and manufacturing, logistics, distribution, sales and customers. A critical aspect of the position is the ability to identify value added opportunities, creatively recognize potential solutions, vet the ideas across the stakeholders and takes a hands on app

Electrical Engineer ---->
Introduction:Design Group is a leading engineering, systems integration, and technology consulting firm, capable of providing complete operating solutions for consumer products, life sciences, and other industrial sectors.  Design Group provides engineering, project management, regulatory compliance, and other technology services to the world’s leading companies.  Our organization is staffed by over1,000 engineering and technical specialists, operating from over 35 offices in the U.S. and Puerto Rico. Design Group provides professional engineering, architectural and construction management ser

In [16]:
selected_titles = {
    'INFORMATION-TECHNOLOGY':'IT Support Technician Job in Madison',
    'FINANCE':'Senior Accountant/Analyst Job in Denver',
    'ENGINEERING':'Quality Engineer Job in Durham',
    'SALES':'Sales Professional Job in Las Vegas',
    'HR':'Human Resources Manager Job in Dallas',
    'HEALTHCARE':'Registered Nurse - Clinic Job in Houston'

}

In [17]:
for category, title in selected_titles.items():
  matches = df_jobs[df_jobs['job_title']==title]
  print(category,' :',title, ' --> matches found', matches.shape[0])

INFORMATION-TECHNOLOGY  : IT Support Technician Job in Madison  --> matches found 1
FINANCE  : Senior Accountant/Analyst Job in Denver  --> matches found 1
ENGINEERING  : Quality Engineer Job in Durham  --> matches found 1
SALES  : Sales Professional Job in Las Vegas  --> matches found 4
HR  : Human Resources Manager Job in Dallas  --> matches found 1
HEALTHCARE  : Registered Nurse - Clinic Job in Houston  --> matches found 1

In [18]:
jd_rows =[]
for category, title in selected_titles.items():
  rows = df_jobs[df_jobs['job_title']==title].iloc[0]
  jd_rows.append({'category': category, 'job_title':rows['job_title'], 'job_description': rows['job_description']})

df_jd = pd.DataFrame(jd_rows)
print(df_jd.shape)
df_jd.to_pickle('/content/drive/MyDrive/Colab Notebooks/Future_ML_03/data/selected_jobs_description.pkl')
print('done')

(6, 3)
done

In [19]:
df_jd

,category,job_title,job_description
0,INFORMATION-TECHNOLOGY,IT Support Technician Job in Madison,TeamSoft is seeing an IT Support Specialist to...
1,FINANCE,Senior Accountant/Analyst Job in Denver,Would you like to grow your accounting and fin...
2,ENGINEERING,Quality Engineer Job in Durham,Experis Engineering has an immediate opening f...
3,SALES,Sales Professional Job in Las Vegas,Aflac Insurance Sales Agent While a career in ...
4,HR,Human Resources Manager Job in Dallas,"Human Resource Manager Salary $55,000 - $75,0..."
5,HEALTHCARE,Registered Nurse - Clinic Job in Houston,Job Description Position Summary: Provides pro...

In [20]:
IT_postings = df_jobs[df_jobs['sector'] == 'IT/Software Development']['job_title'].tolist()
print(IT_postings[:20])

['IT Support Technician Job in Madison', 'Scrum Master Job in Denver', 'QA Testing Analyst Job in Denver', 'Principal Cyber Security Engineer Job in Houston', 'Business Analyst Job in Houston', 'Database Architect Job in Denver', 'PC Technician Job in Arlington', 'Data Center Wintel Admin Job in Dallas', 'Windows System Admin Job in Dallas', 'Recruiter Job in Coppell', 'Solutions Architect- Cloud Solutions Job in Dallas', 'APPLICATION SUPPORT ANALYST Job in Dallas', 'Desktop Release Analyst Job in Dallas', 'Systems Administrator Job in Dallas', 'Sr. .Net Developer Job in Dallas', 'Unix Systems Admin (Solaris preferred) Job in Dallas', 'Front End Developer Job in Plano', 'Sr. Software Systems Engineer Job in Dallas', 'Senior Telecommunications Engineer Job in Washington', 'Contract Implementation Manager Job in Centennial']

In [21]:
candidate_text = df_jobs[df_jobs['job_title']=='Database Architect Job in Denver']['job_description'].iloc[0]
print(candidate_text[:600])

Are you a SQL DB Architect with expertise in creating SQL Server consolidation implementation plans? If so, your knowledge can be used by to help local clients by creating plans to solve SQL Sprawl issues. This is an opportunity to have ownership of a large scale strategy and offers great compensation. To be considered for this role you must possess the following:  Requirements:Experience documenting recommendations and best practices for configuring servers and storage in new environments to support SQL ServerExperience creating a requirements matrix to identify high level business and techni